spring:
  profiles:
    active: local

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    url:
    username:
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    root: INFO
