spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO
